/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DialogPlugin: typeof import('tdesign-vue-next').DialogPlugin
  const MessagePlugin: typeof import('tdesign-vue-next').MessagePlugin
  const TFocusNumberInput: typeof import('tdesign-vue-next').FocusNumberInput
  const TInputNumber: typeof import('tdesign-vue-next').InputNumber
}
